# Generated by Django 5.1.2 on 2024-11-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='username',
        ),
    ]
