# Generated by Django 5.1.2 on 2024-11-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_name_customers_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='username',
            new_name='name',
        ),
    ]
